[package]
name = "bevy-fsim"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = { git = "https://github.com/Jondolf/avian", branch = "main" }
bevy = "0.17"
rand = "0.9.2"
serde = "1.0.228"
toml = "0.9.7"
bevy_atmosphere = "0.13"