[unit]
name = "Su-25T"

[basic]
wing_area = 30.1 # Wing area (sq m)
wingspan = 14.36 # Wing span (m)
length = 15.35 #  Length (m)
height = 5.2 # Height (m)
mach_max = 0.82 
center_of_mass = [0.0, 0.0, 0.6] # x, y, z
moment_of_inertia = [223845.0, 254758.0, 38912.0, -705.0] # Ix, Iy, Iz, Ixy
empty_mass = 9800 # kg
gross_mass = 14440 # kg
number_of_engines = 2

[aerodynamics]
Cy0 = 0.0001 # Zero AoA lift coefficient 
Czbe = -0.016 # Yaw/side force coefficient
cx_gear = 0.012 # Gear drag
cx_brk = 0.06 # Air brake drag
cx_flap = 0.05 # flap drag
cy_flap = 0.3 # flap lift

[aerodynamics.tables]
# coefficients for machs
mach =      [0,         0.4,    0.6,    0.8,    0.9,    1.5]    # machs
cx0 =       [0.025,     0.025,  0.0272, 0.048,  0.0741, 0.0741] # Drag coefficient
Cya =       [0.0817,    0.0817, 0.0872, 0.0816, 0.08,   0.08]   # Lift coefficient
OmxMax =    [0.5,       1.5,    2.5,    3.5,    3.5,    3.5]    # Max roll rate, rad/s
Aldop =     [20,        20,     20,     18,     15,     10]     # Max Alpha, degrees
CyMax =     [1.21,      1.21,   1.26,   0.755,  0.6,    0.6]    # Max lift coefficient

[engine]
idle_rpm = 50.0 # RPM % at idle
fuel_consumption = 0.37 # kg/s
engine_start_time = 60 # Engine startup time (s)

[engine.tables]
# mach with thrust table
mach =                  [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
max_thrust =            [68952.8, 66424.4, 65130.8, 64778.0, 65130.8, 66424.4, 68952.8, 74382.0, 86808.4, 94234.8, 94234.8] # N
throttle_input =        [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
engine_power =          [0.0, 0.01, 0.02, 0.06, 0.08, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0]
engine_power_readout =  [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]

[structure]
front_wheel = [0, -1.12, -3.85]
back_left_wheel = [-1.35, -1.09, 1.51]
back_right_wheel = [1.35, -1.09, 1.51]
left_wing_pos = [-7.18, 0.5, -0.7]
right_wing_pos = [7.18, 0.5, -0.7]
tail_pos = [0.0, 0.0, -0.1]
elevator_pos = [0.0, 0.0, 7.6]
left_aileron_pos = [-7.18, 0.0, -0.6]
right_aileron_pos = [7.18, 0.0, -0.6]
rudder_pos = [0.0, 2.6, 7.18]
left_engine_pos = [-0.716, -0.391, 3.793]
right_engine_pos = [0.716, -0.391, 3.793]